### ISSUE TITLE
Install fails on Ubuntu 16.04 LTS -- pip 8.1.1

### ISSUE THREAD

**Issue by fiveohhh** [exosite/exosite-cli#2]
`exosite` fails to install on Ubuntul 16.04 LTS.   When I upgraded to pip 9.0.1 the problem went away.

~~~
parker@ubuntu:~$ sudo pip install --upgrade exosite
The directory '/home/parker/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/parker/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting exosite
  Downloading exosite-0.24.tar.gz
Requirement already up-to-date: requests==2.7.0 in /usr/local/lib/python2.7/dist-packages (from exosite)
Collecting certifi (from exosite)
  Downloading certifi-2016.9.26-py2.py3-none-any.whl (377kB)
    100% |████████████████████████████████| 378kB 2.5MB/s 
Collecting urllib3>=1.10 (from exosite)
  Downloading urllib3-1.19-py2.py3-none-any.whl (104kB)
    100% |████████████████████████████████| 112kB 4.7MB/s 
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 317, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 448, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 387, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

~~~

**Comment by fiveohhh** [comment]
Problem solved by upgrading to pip 9.0.1
